# training 

epochs: 150
csv_file: "/home/valentin/Desktop/interview_memento_ai/DS-RNN/DS-RNN/nasdaq100_padding.csv"
target: "NDX"
batch_size: 128

timesteps: 10
m_dim: 64
p_dim: 64
num_exogenous: 81

lr: 0.0001
train_split: 0.75
val_split: 0.15

