# training 

epochs: 150
csv_file: "/home/valentin/Desktop/personal_work/memento_interview/DA-RNN/Dual_Stage_attention_RNN/nasdaq100_padding.csv"
target: "NDX"
batch_size: 128

timesteps: 10
m_dim: 64
p_dim: 64
num_exogenous: 81

lr: 0.001
train_split: 0.75
val_split: 0.15

